# Generated by Django 5.1.5 on 2026-02-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebackground',
            name='scene',
            field=models.CharField(choices=[('login', '登录页'), ('home', '首页'), ('script_optimizer', '剧本优化页'), ('profile', '用户信息页')], max_length=32, unique=True),
        ),
    ]
