# Generated by Django 5.1.5 on 2026-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_add_ai_manga_style_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebackground',
            name='scene',
            field=models.CharField(choices=[('login', '登录页'), ('home', '首页'), ('profile', '用户信息页')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='key',
            field=models.CharField(choices=[('default_avatar_url', '默认头像URL'), ('ai_assistant_base_url', '助手模型API地址'), ('ai_assistant_api_key', '助手模型API Key'), ('ai_assistant_model', '助手模型名称'), ('ai_manga_base_url', '剧本模型API地址'), ('ai_manga_api_key', '剧本模型API Key'), ('ai_manga_model', '剧本模型名称'), ('ai_manga_storyboard_prompt', 'AI剧本解析规则'), ('ai_manga_3d_style_prompt', '3D风格提示词'), ('ai_manga_real_style_prompt', '真人风格提示词')], max_length=64, unique=True),
        ),
    ]
