# Generated by Django 5.1.5 on 2026-03-01

from django.db import migrations, models


def forwards(apps, schema_editor):
    Ticket = apps.get_model("ai_customer", "HumanHandoverTicket")
    Ticket.objects.filter(status="open").update(status="unread")
    Ticket.objects.filter(status="resolved").update(status="read")


def backwards(apps, schema_editor):
    Ticket = apps.get_model("ai_customer", "HumanHandoverTicket")
    Ticket.objects.filter(status="unread").update(status="open")
    Ticket.objects.filter(status="read").update(status="resolved")
    Ticket.objects.filter(status="ignored").update(status="resolved")


class Migration(migrations.Migration):

    dependencies = [
        ("ai_customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanhandoverticket",
            name="admin_reply",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="humanhandoverticket",
            name="status",
            field=models.CharField(
                choices=[("unread", "未读"), ("read", "已读"), ("ignored", "忽略")],
                default="unread",
                max_length=16,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
