# Generated by Django 5.1.5 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_customer", "0002_ticket_status_and_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanhandoverticket",
            name="synced_to_knowledge",
            field=models.BooleanField(default=False),
        ),
    ]
