# Generated by Django 5.1.5 on 2026-03-05 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0006_resume_prompt_and_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiHotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='aa1_douyin_hot', max_length=32)),
                ('word', models.CharField(max_length=100, unique=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('hot_value', models.CharField(blank=True, default='', max_length=64)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AiBloggerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_mode', models.CharField(choices=[('manual', '手动'), ('auto', '自动')], default='manual', max_length=16)),
                ('hot_word', models.CharField(max_length=100)),
                ('style_prompt', models.TextField(blank=True, default='')),
                ('ratio', models.CharField(default='9:16', max_length=16)),
                ('image_count', models.PositiveSmallIntegerField(default=1)),
                ('status_text', models.CharField(choices=[('queued', '排队中'), ('running', '处理中'), ('success', '成功'), ('failed', '失败')], default='queued', max_length=16)),
                ('stage_text', models.CharField(choices=[('title', '标题'), ('copy', '文案'), ('images', '配图'), ('done', '完成')], default='title', max_length=16)),
                ('title', models.TextField(blank=True, default='')),
                ('copy', models.TextField(blank=True, default='')),
                ('selected_cover_key', models.CharField(blank=True, default='', max_length=255)),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_blogger_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AiBloggerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=16)),
                ('cos_key', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ai_customer.aibloggerpost')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AiBloggerVideoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_video', models.CharField(choices=[('queued', '排队中'), ('running', '处理中'), ('success', '成功'), ('failed', '失败')], default='queued', max_length=16)),
                ('seedance_task_id', models.CharField(blank=True, default='', max_length=120)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
                ('ratio', models.CharField(default='adaptive', max_length=16)),
                ('generate_audio', models.BooleanField(default=True)),
                ('watermark', models.BooleanField(default=False)),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tasks', to='ai_customer.aibloggerpost')),
                ('video_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_customer.aibloggerasset')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
