# Generated by Django 5.1.5 on 2026-03-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0007_aihotitem_aibloggerpost_aibloggerasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
