# Generated by Django 5.1.5 on 2026-03-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0008_knowledgedocument_source_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=64, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('chunk_size', models.PositiveIntegerField(default=2097152)),
                ('total_chunks', models.PositiveIntegerField(default=1)),
                ('uploaded_chunks', models.JSONField(blank=True, default=list)),
                ('completed_doc_id', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成'), ('aborted', '已取消')], default='uploading', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
