# Generated by Django 5.1.5 on 2026-03-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0009_knowledgeuploadsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='status',
            field=models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败'), ('canceled', '已取消')], default='pending', max_length=16),
        ),
    ]
