# Generated by Django 5.1.5 on 2026-03-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0010_alter_knowledgedocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='status',
            field=models.CharField(choices=[('pending', '排队中'), ('running', '处理中'), ('success', '成功'), ('failed', '失败'), ('canceled', '取消上传')], default='pending', max_length=16),
        ),
    ]
