# Generated by Django 5.1.5 on 2026-03-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0012_chatsession_chatmessage_session_memorychunk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aibloggerpost',
            name='status_text',
            field=models.CharField(choices=[('queued', '排队中'), ('running', '处理中'), ('success', '成功'), ('failed', '失败'), ('canceled', '已取消')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='aibloggervideotask',
            name='status_video',
            field=models.CharField(choices=[('queued', '排队中'), ('running', '处理中'), ('success', '成功'), ('failed', '失败'), ('canceled', '已取消')], default='queued', max_length=16),
        ),
    ]
