# Generated by Django 5.1.5 on 2026-05-30 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0019_storyboard_panel_options_and_position_assets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneInferenceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='场景推理', max_length=255)),
                ('model_key', models.CharField(blank=True, default='gpt-image-2', max_length=100)),
                ('status', models.CharField(choices=[('draft', '待推理'), ('inference_running', '视角推理中'), ('inference_done', '视角推理完成'), ('panorama_running', '全景生成中'), ('panorama_done', '全景完成'), ('failed', '失败')], default='draft', max_length=50)),
                ('front_image_url', models.URLField(max_length=1000)),
                ('back_image_url', models.URLField(max_length=1000)),
                ('left_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('right_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('top_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('panorama_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_inference_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneInferenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('generate_left', '生成左侧面'), ('generate_right', '生成右侧面'), ('generate_top', '生成俯瞰图'), ('generate_panorama', '生成全景图')], max_length=50)),
                ('model_key', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '生成中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=30)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_snapshot', models.TextField(blank=True, default='')),
                ('input_payload', models.JSONField(default=dict)),
                ('output_payload', models.JSONField(default=dict)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ai_customer.sceneinferenceproject')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
