# Generated by Django 5.1.5 on 2026-05-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0020_sceneinferenceproject_sceneinferencejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneinferencejob',
            name='job_type',
            field=models.CharField(choices=[('generate_left', '生成左侧面'), ('generate_right', '生成右侧面'), ('generate_top', '生成俯瞰图'), ('generate_panorama', '生成全景图'), ('enhance_screenshot', '高清修复截屏')], max_length=50),
        ),
    ]
