# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_customer", "0025_octopusnotefolder_octopusnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="octopusnotefolder",
            name="cover_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="octopusnote",
            name="cover_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
