# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_customer", "0026_octopus_covers"),
    ]

    operations = [
        migrations.AddField(
            model_name="octopusnote",
            name="image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
