# Generated by Django 5.1.5 on 2026-06-18 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0027_octopus_note_image_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OctopusPlanetPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('tag_normalized', models.CharField(db_index=True, max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_vector_ready', models.BooleanField(default=False)),
                ('tag_vector', models.JSONField(blank=True, default=list)),
                ('particle_x', models.FloatField(blank=True, null=True)),
                ('particle_y', models.FloatField(blank=True, null=True)),
                ('particle_z', models.FloatField(blank=True, null=True)),
                ('particle_color', models.CharField(blank=True, default='', max_length=20)),
                ('particle_size', models.FloatField(default=1.0)),
                ('qdrant_point_id', models.CharField(max_length=64, unique=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planet_publish', to='ai_customer.octopusnote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='octopus_planet_publishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['user', '-published_at'], name='ai_customer_user_id_42b54b_idx'), models.Index(fields=['is_public', '-published_at'], name='ai_customer_is_publ_c874ad_idx'), models.Index(fields=['tag_normalized'], name='ai_customer_tag_nor_2765e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='OctopusPlanetTagStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('tag_normalized', models.CharField(max_length=20)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='octopus_planet_tag_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-use_count', '-last_used_at'], name='ai_customer_user_id_db2d35_idx')],
                'unique_together': {('user', 'tag_normalized')},
            },
        ),
    ]
