# Generated by Django 5.1.5 on 2026-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_customer', '0028_octopusplanetpublish_octopusplanettagstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='octopusplanetpublish',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='octopusplanetpublish',
            name='tags_normalized',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
