# Generated by Django 5.1.5 on 2026-03-01 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(blank=True, default='', max_length=120)),
                ('filename', models.CharField(blank=True, default='', max_length=300)),
                ('content_type', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', '成功'), ('rejected', '拒绝'), ('error', '错误')], default='success', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
