from django.urls import path

from apps.ai_customer.views import (
    ai_manga_config,
    ai_manga_storyboard,
    ai_manga_storyboard_image,
    chat_history,
    chat_sessions,
    chat_session_activate,
    chat_stream,
    human_replies,
    memory_facts,
    memory_summary,
    clear_human_replies,
)
from apps.ai_customer.admin_views import (
    ai_cs_docs,
    ai_cs_doc_cancel,
    ai_cs_doc_delete,
    ai_cs_settings,
    ai_cs_upload_knowledge_chunk,
    ai_cs_upload_knowledge_complete,
    ai_cs_upload_knowledge_init,
    ai_cs_upload_knowledge_status,
    ai_cs_ticket_sync_knowledge,
    ai_cs_tickets,
    ai_cs_ticket_update,
    ai_cs_upload_knowledge,
    ai_memory_admin_overview,
    ai_memory_fact_inactivate,
    ai_memory_summary_rebuild,
)

urlpatterns = [
    path("ai-manga/config", ai_manga_config),
    path("ai-manga/storyboard", ai_manga_storyboard),
    path("ai-manga/storyboard-image", ai_manga_storyboard_image),
    path("ai-customer/history", chat_history),
    path("ai-customer/sessions", chat_sessions),
    path("ai-customer/sessions/<int:session_id>/activate", chat_session_activate),
    path("ai-customer/human-replies", human_replies),
    path("ai-customer/human-replies/clear", clear_human_replies),
    path("ai-customer/memory/summary", memory_summary),
    path("ai-customer/memory/facts", memory_facts),
    path("ai-customer/chat/stream", chat_stream),

    path("console/ai-cs/settings", ai_cs_settings),
    path("console/ai-cs/knowledge/docs", ai_cs_docs),
    path("console/ai-cs/knowledge/upload", ai_cs_upload_knowledge),
    path("console/ai-cs/knowledge/upload/init", ai_cs_upload_knowledge_init),
    path("console/ai-cs/knowledge/upload/chunk", ai_cs_upload_knowledge_chunk),
    path("console/ai-cs/knowledge/upload/status", ai_cs_upload_knowledge_status),
    path("console/ai-cs/knowledge/upload/complete", ai_cs_upload_knowledge_complete),
    path("console/ai-cs/knowledge/docs/<int:doc_id>/cancel", ai_cs_doc_cancel),
    path("console/ai-cs/knowledge/docs/<int:doc_id>", ai_cs_doc_delete),
    path("console/ai-cs/tickets", ai_cs_tickets),
    path("console/ai-cs/tickets/sync-knowledge", ai_cs_ticket_sync_knowledge),
    path("console/ai-cs/tickets/<int:ticket_id>", ai_cs_ticket_update),
    path("console/ai-memory/overview", ai_memory_admin_overview),
    path("console/ai-memory/summaries/<int:session_id>/rebuild", ai_memory_summary_rebuild),
    path("console/ai-memory/facts/<int:fact_id>/inactivate", ai_memory_fact_inactivate),
]
