from django.urls import path

from apps.ai_customer.views import (
    ai_image_cutout,
    ai_image_cutout_asset,
    ai_image_cutout_asset_delete,
    ai_image_cutout_assets,
    ai_image_sticker_composition_enhance,
    ai_image_sticker_composition_delete,
    ai_image_sticker_compositions,
    octopus_note_detail,
    octopus_note_folder_detail,
    octopus_note_folders,
    octopus_notes,
    scene_inference_enhance_screenshot,
    scene_inference_generate_panorama,
    scene_inference_generate_views,
    scene_inference_project_detail,
    scene_inference_projects,
    scene_inference_refresh,
    storyboard_config,
    storyboard_project_analyze,
    storyboard_project_segments,
    storyboard_projects,
    storyboard_panel_regenerate,
    storyboard_panel_update,
    storyboard_segment_assets,
    storyboard_segment_asset_delete,
    storyboard_segment_assets_required,
    storyboard_segment_compose_grid,
    storyboard_segment_generate_images,
    storyboard_segment_generate_panels,
    storyboard_segment_generate_video_prompts,
    storyboard_segment_refresh_images,
)

urlpatterns = [
    path("octopus-note/folders", octopus_note_folders),
    path("octopus-note/folders/<int:folder_id>", octopus_note_folder_detail),
    path("octopus-note/folders/<int:folder_id>/notes", octopus_notes),
    path("octopus-note/notes/<int:note_id>", octopus_note_detail),
    path("storyboard/config", storyboard_config),
    path("storyboard/projects", storyboard_projects),
    path("storyboard/projects/<int:project_id>/analyze", storyboard_project_analyze),
    path("storyboard/projects/<int:project_id>/segments", storyboard_project_segments),
    path("storyboard/segments/<int:segment_id>/assets-required", storyboard_segment_assets_required),
    path("storyboard/segments/<int:segment_id>/assets", storyboard_segment_assets),
    path("storyboard/segments/<int:segment_id>/assets/<int:asset_id>", storyboard_segment_asset_delete),
    path("storyboard/segments/<int:segment_id>/generate-panels", storyboard_segment_generate_panels),
    path("storyboard/segments/<int:segment_id>/generate-panel-images", storyboard_segment_generate_images),
    path("storyboard/segments/<int:segment_id>/generate-video-prompts", storyboard_segment_generate_video_prompts),
    path("storyboard/segments/<int:segment_id>/panel-images/refresh", storyboard_segment_refresh_images),
    path("storyboard/segments/<int:segment_id>/compose-grid", storyboard_segment_compose_grid),
    path("storyboard/panels/<int:panel_id>", storyboard_panel_update),
    path("storyboard/panels/<int:panel_id>/regenerate", storyboard_panel_regenerate),
    path("ai-image/cutout", ai_image_cutout),
    path("ai-image/cutout-asset", ai_image_cutout_asset),
    path("ai-image/cutout-assets", ai_image_cutout_assets),
    path("ai-image/cutout-assets/<int:asset_id>", ai_image_cutout_asset_delete),
    path("ai-image/sticker-compositions", ai_image_sticker_compositions),
    path("ai-image/sticker-compositions/enhance", ai_image_sticker_composition_enhance),
    path("ai-image/sticker-compositions/<int:composition_id>", ai_image_sticker_composition_delete),
    path("scene-inference/projects", scene_inference_projects),
    path("scene-inference/projects/<int:project_id>", scene_inference_project_detail),
    path("scene-inference/projects/<int:project_id>/generate-views", scene_inference_generate_views),
    path("scene-inference/projects/<int:project_id>/generate-panorama", scene_inference_generate_panorama),
    path("scene-inference/projects/<int:project_id>/refresh", scene_inference_refresh),
    path("scene-inference/projects/<int:project_id>/screenshot/enhance", scene_inference_enhance_screenshot),
]
