from django.urls import path

from apps.ai_customer.views import (
    ai_image_cutout,
    ai_image_cutout_asset,
    ai_image_cutout_asset_delete,
    ai_image_cutout_assets,
    ai_image_config,
    ai_image_generate,
    ai_image_task,
    storyboard_config,
    storyboard_project_analyze,
    storyboard_project_segments,
    storyboard_projects,
    storyboard_segment_assets,
    storyboard_segment_assets_required,
    storyboard_segment_compose_grid,
    storyboard_segment_generate_images,
    storyboard_segment_generate_panels,
    storyboard_segment_refresh_images,
)

urlpatterns = [
    path("storyboard/config", storyboard_config),
    path("storyboard/projects", storyboard_projects),
    path("storyboard/projects/<int:project_id>/analyze", storyboard_project_analyze),
    path("storyboard/projects/<int:project_id>/segments", storyboard_project_segments),
    path("storyboard/segments/<int:segment_id>/assets-required", storyboard_segment_assets_required),
    path("storyboard/segments/<int:segment_id>/assets", storyboard_segment_assets),
    path("storyboard/segments/<int:segment_id>/generate-panels", storyboard_segment_generate_panels),
    path("storyboard/segments/<int:segment_id>/generate-panel-images", storyboard_segment_generate_images),
    path("storyboard/segments/<int:segment_id>/panel-images/refresh", storyboard_segment_refresh_images),
    path("storyboard/segments/<int:segment_id>/compose-grid", storyboard_segment_compose_grid),
    path("ai-image/config", ai_image_config),
    path("ai-image/generate", ai_image_generate),
    path("ai-image/cutout", ai_image_cutout),
    path("ai-image/cutout-asset", ai_image_cutout_asset),
    path("ai-image/cutout-assets", ai_image_cutout_assets),
    path("ai-image/cutout-assets/<int:asset_id>", ai_image_cutout_asset_delete),
    path("ai-image/tasks/<str:task_id>", ai_image_task),
]
