# Generated by Django 5.1.5 on 2026-02-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
