# Generated by Django 5.1.5 on 2026-03-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_pointsusagelog_usage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsusagelog',
            name='usage_type',
            field=models.CharField(choices=[('script_storyboard', '剧本分镜消耗'), ('paragraph_storyboard', '段落分镜消耗'), ('resume_assistant', '简历助手消耗'), ('ai_blogger_post', '章鱼博主图文生成'), ('ai_blogger_video', '章鱼博主视频生成'), ('refund', '失败退款')], max_length=32),
        ),
    ]
