# Generated by Django 5.1.5 on 2026-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsusagelog',
            name='usage_type',
            field=models.CharField(choices=[('refund', '失败退款')], max_length=32),
        ),
    ]
