# Generated by Django 5.1.5 on 2026-05-30 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiScriptBreakdownProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('script_text', models.TextField()),
                ('selected_style', models.CharField(choices=[('live_action', '真人写实'), ('anime_3d', '3D动漫')], default='live_action', max_length=32)),
                ('max_segment_seconds', models.PositiveIntegerField(default=15)),
                ('analysis_model', models.CharField(blank=True, default='deepseek-v4-pro', max_length=100)),
                ('status', models.CharField(choices=[('pending', '待拆解'), ('processing', '拆解中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('extracted_assets_json', models.JSONField(default=dict)),
                ('validation_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_breakdown_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AiScriptAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('scene', '场景'), ('character', '角色'), ('prop', '道具')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, default='', max_length=255)),
                ('file_url', models.URLField(blank=True, default='', max_length=1000)),
                ('ai_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ai_script_breakdown.aiscriptbreakdownproject')),
            ],
            options={
                'ordering': ['asset_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiScriptSceneBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(max_length=255)),
                ('scene_description', models.TextField(blank=True, default='')),
                ('front_view_description', models.TextField(blank=True, default='')),
                ('reverse_view_description', models.TextField(blank=True, default='')),
                ('original_text', models.TextField(blank=True, default='')),
                ('characters', models.JSONField(default=list)),
                ('props', models.JSONField(default=list)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_blocks', to='ai_script_breakdown.aiscriptbreakdownproject')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiScriptShotSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_title', models.CharField(max_length=255)),
                ('estimated_duration', models.PositiveIntegerField(default=0)),
                ('style_prompt', models.TextField(blank=True, default='')),
                ('copy_text', models.TextField(blank=True, default='')),
                ('continuity_from_previous', models.BooleanField(default=False)),
                ('previous_anchor_line', models.TextField(blank=True, default='')),
                ('scene_view', models.CharField(choices=[('front', '正面'), ('reverse', '反打'), ('side', '侧面'), ('closeup', '近景'), ('mixed', '混合')], default='front', max_length=32)),
                ('characters', models.JSONField(default=list)),
                ('props', models.JSONField(default=list)),
                ('position_image_prompt', models.TextField(blank=True, default='')),
                ('position_layout_json', models.JSONField(default=dict)),
                ('position_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_segments', to='ai_script_breakdown.aiscriptbreakdownproject')),
                ('scene_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='ai_script_breakdown.aiscriptsceneblock')),
            ],
            options={
                'ordering': ['scene_block__order_index', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiScriptShotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_size', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('dialogue', models.TextField(blank=True, default='')),
                ('line_text', models.TextField(blank=True, default='')),
                ('is_continuity_anchor', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_lines', to='ai_script_breakdown.aiscriptshotsegment')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
