# Generated by Django 5.1.5 on 2026-05-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_script_breakdown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscriptsceneblock',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aiscriptsceneblock',
            name='scene_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aiscriptsceneblock',
            name='time_of_day',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
