# Generated by Django 5.1.5 on 2026-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_script_breakdown', '0002_aiscriptsceneblock_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscriptshotsegment',
            name='position_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiscriptshotsegment',
            name='position_generation_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aiscriptshotsegment',
            name='position_image_model',
            field=models.CharField(blank=True, default='gpt-image-2', max_length=100),
        ),
    ]
