# Generated by Django 5.1.5 on 2026-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_script_breakdown', '0003_aiscriptshotsegment_position_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscriptshotsegment',
            name='position_reference_asset_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='aiscriptasset',
            name='asset_type',
            field=models.CharField(choices=[('scene', '场景'), ('character', '角色'), ('prop', '道具'), ('reference', '参考图')], max_length=32),
        ),
    ]
