# Generated by Django 5.1.5 on 2026-03-07 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('scene', models.CharField(default='general', max_length=64)),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '归档')], default='active', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_mem_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_sessions',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('token_estimate', models.IntegerField(default=0)),
                ('message_type', models.CharField(default='chat', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_mem_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_memory.aisession')),
            ],
            options={
                'db_table': 'ai_messages',
            },
        ),
        migrations.CreateModel(
            name='AIMemoryWriteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_message_id', models.BigIntegerField(default=0)),
                ('decision', models.CharField(max_length=32)),
                ('target_layer', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_mem_write_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_logs', to='ai_memory.aisession')),
            ],
            options={
                'db_table': 'ai_memory_write_logs',
            },
        ),
        migrations.CreateModel(
            name='AIConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('recent_context', '近期脉络')], default='recent_context', max_length=32)),
                ('task_stage', models.CharField(blank=True, default='', max_length=64)),
                ('current_goal', models.CharField(blank=True, default='', max_length=500)),
                ('recent_decisions', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('important_entities', models.JSONField(blank=True, default=list)),
                ('next_action', models.CharField(blank=True, default='', max_length=500)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_mem_summaries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='ai_memory.aisession')),
            ],
            options={
                'db_table': 'ai_conversation_summaries',
            },
        ),
        migrations.CreateModel(
            name='AIUserFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_key', models.CharField(max_length=128)),
                ('fact_value', models.TextField()),
                ('fact_type', models.CharField(default='general', max_length=64)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.8, max_digits=4)),
                ('source', models.CharField(default='model_extract', max_length=32)),
                ('status', models.CharField(choices=[('active', '生效'), ('inactive', '失效'), ('deleted', '删除')], default='active', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_mem_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_user_facts',
            },
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['user', 'last_active_at'], name='ai_sessions_user_id_14023b_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['status'], name='ai_sessions_status_62c431_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_messages_session_7725d6_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['user', 'created_at'], name='ai_messages_user_id_29165d_idx'),
        ),
        migrations.AddIndex(
            model_name='aimemorywritelog',
            index=models.Index(fields=['user', 'created_at'], name='ai_memory_w_user_id_961298_idx'),
        ),
        migrations.AddIndex(
            model_name='aimemorywritelog',
            index=models.Index(fields=['session', 'created_at'], name='ai_memory_w_session_b3253b_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationsummary',
            index=models.Index(fields=['session', 'is_active'], name='ai_conversa_session_de4024_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationsummary',
            index=models.Index(fields=['user', 'is_active'], name='ai_conversa_user_id_677d45_idx'),
        ),
        migrations.AddIndex(
            model_name='aiuserfact',
            index=models.Index(fields=['user', 'fact_type'], name='ai_user_fac_user_id_539a51_idx'),
        ),
        migrations.AddIndex(
            model_name='aiuserfact',
            index=models.Index(fields=['user', 'status'], name='ai_user_fac_user_id_25eafc_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiuserfact',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'fact_key'), name='uniq_ai_user_fact_active'),
        ),
    ]
